/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
*
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
*
 * Boost Software License - Version 1.0 - August 17th, 2003
*
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
*
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
*
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cyhal.h"
#include "cybsp.h"
#include "secure_config.h"
#include "keystorage.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* location info provided from linker */
extern const char __si_addr_linker_symbol[];
extern const char __si_size_linker_symbol[];
extern const char __si_vector_offset_linker_symbol[];

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* App version */
#define SI_VERSION_MAJOR    (0UL)                                           /* Major version */
#define SI_VERSION_MINOR    (0UL)                                           /* Minor version */

#define SI_ADDR             ((uint32_t)__si_addr_linker_symbol)
#define SI_SIZE             ((uint32_t)__si_size_linker_symbol)
#define SI_VECTOR_OFFSET    ((uint32_t)__si_vector_offset_linker_symbol)
#define SI_VT_OFFSET        (SI_VECTOR_OFFSET) \
                                - offsetof(CYSAF_APPHEADER_Type, core0Vt)   /* VT Offset */
#define SI_CPUID            (0xC2400000UL)                                  /* CM7_0 ARM CPUID[15:4] Reg shifted to [31:20] */
#define SI_CORE_IDX         (0UL)                                           /* Index ID of the CM0+ core */

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/* Secure Application header for the CodeFlash application */
CY_SECTION(".cy_app_header") __USED
static const CYSAF_APPHEADER_Type CYSAF_HEADER =
{
    .objSize        = SI_SIZE,
    .appId          = (SI_APP_VERSION(SI_VERSION_MAJOR, SI_VERSION_MINOR) | SI_APP_ID_SECUREIMG),
    .appAttributes  = 0UL,                                                  /* Reserved */
    .numCores       = 1UL,
    .core0Vt        = SI_VT_OFFSET,                                         /* VT offset */
    .core0Id        = SI_CPUID | SI_CORE_IDX,                               /* core ID */
};

/* Secure Image Digital signature (Populated by cymcuelftool) */
CY_SECTION(".cy_app_signature") __USED CY_ALIGN(4)
static const uint8_t appSignature[SI_SECURE_DIGSIG_SIZE] = {0u};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Retrun:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    /* Enable global interrupts */
    __enable_irq();

    for (;;)
    {
        ;
    }
}

/* [] END OF FILE */
