/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"
#include "secure_config.h"
#include "keystorage.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* location info provided from linker */
extern const char __si_addr_linker_symbol[];
extern const char __si_size_linker_symbol[];
extern const char __si_vector_offset_linker_symbol[];
extern const char __si_cm7_0_app_address[];
extern const char __si_cm7_1_app_address[];

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define VERIFYAPP_ADDR      (0x17002040)
#define PUBLIC_KEY_ADDR     (0x17006408)

/* App version */
#define SI_VERSION_MAJOR    (0UL)                                           /* Major version */
#define SI_VERSION_MINOR    (0UL)                                           /* Minor version */

#define SI_ADDR             ((uint32_t)__si_addr_linker_symbol)
#define SI_SIZE             ((uint32_t)__si_size_linker_symbol)
#define SI_VECTOR_OFFSET    ((uint32_t)__si_vector_offset_linker_symbol)
#define SI_VT_OFFSET        (SI_VECTOR_OFFSET) \
                                - offsetof(CYSAF_APPHEADER_Type, core0Vt)   /* CM0+ VT Offset */
#define SI_CPUID            (0xC6000000UL)                                  /* CM0+ ARM CPUID[15:4] Reg shifted to [31:20] */
#define SI_CORE_IDX         (0UL)                                           /* Index ID of the CM0+ core */

/* Flashboot parameters */
#define SI_FLASHBOOT_FLAGS  ((SI_FLASHBOOT_CLK_50MHZ << SI_TOC_FLAGS_CLOCKS_POS) \
                                | (SI_FLASHBOOT_WAIT_20MS << SI_TOC_FLAGS_DELAY_POS) \
                                | (SI_FLASHBOOT_SWJ_ENABLE << SI_TOC_FLAGS_SWJEN_POS) \
                                | (SI_FLASHBOOT_VALIDATE_DISABLE << SI_TOC_FLAGS_APP_VERIFY_POS) \
                                | (SI_FLASHBOOT_FBLOADER_DISABLE << SI_TOC_FLAGS_FBLOADER_ENABLE_POS))

#define SECTOR_SIZE         (0x8000UL)

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/* TOC2 */
CY_SECTION(".cy_toc_part2") __USED
static const SFLASH_TOC2_Type SFLASH_TOC2 =
{
    .TOC2_OBJECT_SIZE                   = SI_TOC2_OBJECTSIZE,
    .TOC2_MAGIC_NUMBER                  = SI_TOC2_MAGICNUMBER,
    .TOC2_SMIF_CFG_STRUCT_ADDR          = 0UL,
    .TOC2_FIRST_USER_APP_ADDR           = SI_ADDR,                          /* top address of CM0+ app */
    .TOC2_FIRST_USER_APP_FORMAT         = SI_APP_FORMAT_CYPRESS,            /* format of CM0+ app */
    .TOC2_SECOND_USER_APP_ADDR          = 0UL,                              /* not used */
    .TOC2_SECOND_USER_APP_FORMAT        = 0UL,                              /* basic */
    .TOC2_FIRST_CMX_1_USER_APP_ADDR     = 0UL,                              /* not verified by Flash Boot*/
    .TOC2_SECOND_CMX_1_USER_APP_ADDR    = 0UL,                              /* nused */
    .TOC2_FIRST_CMX_2_USER_APP_ADDR     = 0UL,                              /* not verified by Flash Boot*/
    .TOC2_SECOND_CMX_2_USER_APP_ADDR    = 0UL,                              /* not used */
    .RESERVED14                         = {0UL},
    .TOC2_SECURITY_UPDATES_MARKER       = 0UL,                              /* disable PPUs configuration */
    .TOC2_SHASH_OBJECTS                 = 3UL,                              /* KEY + APP_PROTECTION + TOC2 */
    .TOC2_SIGNATURE_VERIF_KEY           = SI_PUBLIC_KEY,
    .TOC2_APP_PROTECTION_ADDR           = SI_SWPU_BEGIN,                    /* this area shall not be modified */
    .RESERVED15                         = {0UL},
    .TOC2_REVISION                      = 0UL,                              /* not used */
    .TOC2_FLAGS                         = SI_FLASHBOOT_FLAGS,
};

/* Public Key */
CY_SECTION(".cy_sflash_public_key") __USED
static const PUBLIC_KEY_Type PUBLIC_KEY =
{
    .objSize = sizeof(PUBLIC_KEY_Type),
    .signatureScheme = SI_PUBLIC_KEY_RSA_2048,
    .publicKeyStruct =
    {
        .moduloAddr         = SI_PUBLIC_KEY + offsetof(PUBLIC_KEY_Type, moduloData),
        .moduloSize         = SI_PUBLIC_KEY_SIZEOF_BYTE * SI_PUBLIC_KEY_MODULOLENGTH,
        .expAddr            = SI_PUBLIC_KEY + offsetof(PUBLIC_KEY_Type, expData),
        .expSize            = SI_PUBLIC_KEY_SIZEOF_BYTE * SI_PUBLIC_KEY_EXPLENGTH,
        .barrettAddr        = SI_PUBLIC_KEY + offsetof(PUBLIC_KEY_Type, barrettData),
        .inverseModuloAddr  = SI_PUBLIC_KEY + offsetof(PUBLIC_KEY_Type, inverseModuloData),
        .rBarAddr           = SI_PUBLIC_KEY + offsetof(PUBLIC_KEY_Type, rBarData),
    },

    .moduloData =
    {
        0x21u, 0xE0u, 0x32u, 0x21u, 0x27u, 0x5Au, 0x01u, 0x75u,
        0xE1u, 0x41u, 0x53u, 0xDAu, 0xA6u, 0x8Cu, 0x83u, 0xEAu,
        0x90u, 0xCBu, 0xCCu, 0x89u, 0xECu, 0x87u, 0x52u, 0xBFu,
        0xB6u, 0xA3u, 0xB8u, 0xD3u, 0x0Fu, 0xDBu, 0xC8u, 0xEEu,
        0x5Fu, 0x25u, 0x7Cu, 0x8Fu, 0xFEu, 0xF7u, 0x79u, 0xE1u,
        0x6Bu, 0xC4u, 0x83u, 0x46u, 0x82u, 0xACu, 0x3Du, 0x16u,
        0x79u, 0x59u, 0x1Fu, 0x24u, 0x59u, 0x43u, 0xF7u, 0x29u,
        0x99u, 0x04u, 0xABu, 0xD9u, 0x58u, 0x58u, 0xFAu, 0xBEu,
        0xE5u, 0x2Fu, 0x67u, 0x5Au, 0x19u, 0x0Fu, 0x9Au, 0x99u,
        0xD4u, 0x74u, 0x9Fu, 0x8Cu, 0xA3u, 0x44u, 0x8Fu, 0x61u,
        0xD5u, 0x9Fu, 0x76u, 0x8Cu, 0x51u, 0xBBu, 0xD6u, 0xCEu,
        0x3Cu, 0x11u, 0x3Au, 0xBDu, 0x9Eu, 0xF0u, 0x88u, 0xBBu,
        0xB2u, 0x54u, 0xB9u, 0xDAu, 0x46u, 0x22u, 0x62u, 0xFDu,
        0xF3u, 0x05u, 0x99u, 0x2Au, 0x93u, 0x8Bu, 0x31u, 0x05u,
        0xA6u, 0xFBu, 0x35u, 0x49u, 0x54u, 0xEEu, 0x0Bu, 0xDDu,
        0x18u, 0x0Au, 0x5Bu, 0x01u, 0x09u, 0x5Cu, 0xDAu, 0x4Du,
        0x5Eu, 0x1Cu, 0x21u, 0x0Au, 0xD6u, 0xFAu, 0x1Fu, 0x99u,
        0xA2u, 0x4Du, 0xEEu, 0x2Eu, 0xEDu, 0xEDu, 0x65u, 0xCBu,
        0x61u, 0xC3u, 0x34u, 0xAFu, 0x7Au, 0x27u, 0xCDu, 0xD2u,
        0x28u, 0x58u, 0x34u, 0x1Fu, 0x94u, 0x15u, 0xE7u, 0xD8u,
        0x1Au, 0x1Eu, 0x10u, 0x73u, 0xC8u, 0x65u, 0x57u, 0x64u,
        0x4Bu, 0x87u, 0xE7u, 0x32u, 0x9Bu, 0x5Eu, 0xDFu, 0x8Bu,
        0xF2u, 0x7Au, 0x2Au, 0x48u, 0xCDu, 0x3Du, 0x7Du, 0x11u,
        0x54u, 0x63u, 0x1Du, 0xB1u, 0x62u, 0x04u, 0x64u, 0x1Fu,
        0x1Cu, 0x3Au, 0x6Au, 0x8Cu, 0x16u, 0x1Bu, 0xAEu, 0x5Bu,
        0xD7u, 0x65u, 0x4Bu, 0x12u, 0x1Au, 0xB9u, 0x42u, 0x89u,
        0x72u, 0x16u, 0x8Fu, 0x70u, 0x6Du, 0x9Fu, 0x88u, 0x61u,
        0x80u, 0x90u, 0xBAu, 0x38u, 0x78u, 0xFDu, 0x79u, 0x60u,
        0x54u, 0x11u, 0x8Bu, 0xD4u, 0x20u, 0x4Bu, 0x8Au, 0xF2u,
        0xD5u, 0x29u, 0x4Bu, 0x11u, 0x9Cu, 0x8Fu, 0xBAu, 0x31u,
        0x1Fu, 0x13u, 0x11u, 0xFEu, 0x54u, 0x20u, 0xCAu, 0xEBu,
        0xB5u, 0x15u, 0x65u, 0xE9u, 0x53u, 0x3Eu, 0x95u, 0xD3u,
    },
    .expData =
    {
        0x01u, 0x00u, 0x01u, 0x00u,
    },
    .barrettData =
    {
        0x47u, 0x66u, 0xC3u, 0x2Fu, 0xD5u, 0xC8u, 0x23u, 0xD3u,
        0x3Du, 0x46u, 0xC4u, 0x39u, 0x17u, 0x5Bu, 0x45u, 0x09u,
        0x9Bu, 0x22u, 0x5Du, 0xE6u, 0x26u, 0x70u, 0x43u, 0x26u,
        0xEFu, 0xE6u, 0xE5u, 0xD1u, 0xBFu, 0x3Au, 0x61u, 0xFDu,
        0x93u, 0xE4u, 0x88u, 0xA7u, 0x68u, 0xE4u, 0xEAu, 0x9Au,
        0x1Eu, 0x4Cu, 0x86u, 0x87u, 0x09u, 0x28u, 0x21u, 0x99u,
        0x29u, 0xB2u, 0x6Cu, 0x27u, 0x48u, 0x87u, 0x43u, 0x00u,
        0xE9u, 0x6Du, 0xEDu, 0x89u, 0xD7u, 0xC6u, 0xDEu, 0xBAu,
        0x87u, 0x66u, 0x75u, 0x79u, 0x7Du, 0x49u, 0x68u, 0xC8u,
        0x33u, 0xCEu, 0x49u, 0x62u, 0xACu, 0x70u, 0xBFu, 0x97u,
        0x5Eu, 0x6Bu, 0x64u, 0xEEu, 0xCDu, 0x5Eu, 0x04u, 0xD2u,
        0xC3u, 0x2Bu, 0x4Du, 0x28u, 0x32u, 0x3Du, 0xB4u, 0xEFu,
        0x8Du, 0x06u, 0xB1u, 0x38u, 0xADu, 0x5Bu, 0xEDu, 0xD8u,
        0x36u, 0x39u, 0x35u, 0x34u, 0xD4u, 0xAEu, 0x8Du, 0xF7u,
        0xC0u, 0x19u, 0xFBu, 0x0Au, 0xF0u, 0x94u, 0x02u, 0xC3u,
        0x20u, 0x78u, 0x95u, 0x46u, 0xA6u, 0x12u, 0x69u, 0xEDu,
        0x71u, 0x62u, 0x33u, 0xB8u, 0xC3u, 0x86u, 0xCCu, 0x79u,
        0x7Eu, 0x66u, 0x5Eu, 0xA7u, 0xCEu, 0x61u, 0xB7u, 0xA8u,
        0x39u, 0xE9u, 0x66u, 0x30u, 0x32u, 0xD1u, 0xFAu, 0x47u,
        0xB3u, 0x61u, 0x7Bu, 0x31u, 0x5Eu, 0xB7u, 0xB4u, 0x92u,
        0xECu, 0xC2u, 0x56u, 0x29u, 0xEDu, 0xB3u, 0x19u, 0x1Du,
        0x24u, 0x51u, 0x94u, 0x37u, 0xD0u, 0x18u, 0xA4u, 0x0Eu,
        0x02u, 0x70u, 0xC9u, 0x9Cu, 0x03u, 0xE6u, 0x34u, 0x99u,
        0x5Du, 0xB1u, 0x40u, 0x46u, 0xC1u, 0x70u, 0xA5u, 0x70u,
        0xCBu, 0x79u, 0xF9u, 0x16u, 0xFEu, 0x1Du, 0x13u, 0x61u,
        0x90u, 0x1Cu, 0xF2u, 0x17u, 0x72u, 0xE1u, 0x11u, 0x21u,
        0xAAu, 0x13u, 0x13u, 0x54u, 0x84u, 0x68u, 0x9Au, 0xCBu,
        0x70u, 0x87u, 0xA0u, 0x59u, 0xC6u, 0x9Du, 0x43u, 0x62u,
        0x74u, 0x7Bu, 0xD9u, 0x52u, 0x6Bu, 0xC9u, 0x9Cu, 0x15u,
        0x37u, 0x48u, 0xF3u, 0xA7u, 0x0Cu, 0x80u, 0x78u, 0xEBu,
        0x3Bu, 0x1Fu, 0xDFu, 0x47u, 0x37u, 0x46u, 0xA4u, 0xC0u,
        0x16u, 0xE1u, 0x23u, 0x31u, 0x8Eu, 0xC9u, 0xBDu, 0x35u,
        0x01u, 0x00u, 0x00u, 0x00u,
    },
    .inverseModuloData =
    {
        0x1Fu, 0x5Cu, 0xEBu, 0x74u, 0xD2u, 0x43u, 0x75u, 0xE0u,
        0x68u, 0xABu, 0x5Fu, 0xD6u, 0x0Du, 0xEAu, 0xBAu, 0x34u,
        0x4Au, 0x95u, 0x81u, 0xDAu, 0xFEu, 0x9Au, 0xA2u, 0x77u,
        0x19u, 0xCCu, 0x98u, 0x92u, 0x00u, 0x97u, 0xE9u, 0xBEu,
        0x85u, 0x38u, 0xAFu, 0xA1u, 0xD7u, 0x66u, 0xD3u, 0x3Eu,
        0xBBu, 0x4Bu, 0x41u, 0xDEu, 0x7Du, 0xAEu, 0x9Bu, 0x3Au,
        0x8Au, 0xEEu, 0x06u, 0x93u, 0xB3u, 0xB7u, 0x27u, 0x63u,
        0xEDu, 0x9Cu, 0xB9u, 0x3Fu, 0x09u, 0x1Bu, 0x62u, 0xB6u,
        0x18u, 0x87u, 0x99u, 0x0Eu, 0x15u, 0x60u, 0x19u, 0xD4u,
        0x2Eu, 0x77u, 0xC1u, 0x84u, 0x92u, 0x31u, 0xAEu, 0x1Fu,
        0x2Du, 0xB6u, 0x64u, 0x8Fu, 0xBFu, 0x08u, 0x18u, 0x8Fu,
        0x58u, 0x2Cu, 0x9Bu, 0x68u, 0x85u, 0x46u, 0x89u, 0xEBu,
        0x73u, 0x66u, 0x58u, 0x68u, 0x07u, 0x22u, 0x5Cu, 0x19u,
        0xA5u, 0x57u, 0xCBu, 0x89u, 0x03u, 0xE9u, 0xB3u, 0xA0u,
        0x3Bu, 0x7Du, 0x0Bu, 0xACu, 0xBCu, 0xC4u, 0xFDu, 0x79u,
        0x17u, 0x04u, 0x06u, 0x30u, 0x43u, 0x19u, 0x2Bu, 0x52u,
        0xCCu, 0x93u, 0x13u, 0xAAu, 0x6Au, 0x3Fu, 0x57u, 0xEEu,
        0xB7u, 0x98u, 0x79u, 0x7Fu, 0x2Bu, 0x47u, 0x5Du, 0xF3u,
        0xFFu, 0xDFu, 0x6Fu, 0xC6u, 0xCDu, 0x32u, 0x76u, 0xEAu,
        0x87u, 0x87u, 0x2Du, 0x6Du, 0x84u, 0x31u, 0x9Du, 0xD2u,
        0x78u, 0xB8u, 0xCFu, 0xC6u, 0xDBu, 0xE6u, 0x68u, 0x6Du,
        0xA1u, 0x47u, 0x4Du, 0xD6u, 0x60u, 0x66u, 0x9Du, 0x89u,
        0xD2u, 0xDBu, 0xBFu, 0x54u, 0xFDu, 0x69u, 0xF9u, 0x37u,
        0x5Fu, 0xFAu, 0xDAu, 0xB1u, 0x91u, 0x49u, 0x00u, 0xAEu,
        0x01u, 0x63u, 0xD5u, 0xAFu, 0x8Bu, 0xB7u, 0x9Eu, 0x1Fu,
        0x3Eu, 0x5Au, 0xF0u, 0xA6u, 0xEBu, 0x27u, 0x03u, 0xC1u,
        0xEBu, 0x96u, 0xC7u, 0x35u, 0x03u, 0xA0u, 0xA2u, 0x06u,
        0x3Du, 0x94u, 0xB8u, 0xCBu, 0x9Fu, 0x59u, 0x7Du, 0x57u,
        0x63u, 0xFCu, 0xF4u, 0xA2u, 0x2Du, 0xA8u, 0xC4u, 0x04u,
        0xECu, 0xE6u, 0x7Fu, 0x35u, 0x51u, 0x97u, 0x37u, 0xF1u,
        0x2Bu, 0x46u, 0x7Bu, 0xB4u, 0xFBu, 0xDAu, 0x7Au, 0x5Bu,
        0x44u, 0x9Au, 0x71u, 0xD0u, 0xFCu, 0xBAu, 0xE6u, 0xE8u,
    },
    .rBarData =
    {
        0xDFu, 0x1Fu, 0xCDu, 0xDEu, 0xD8u, 0xA5u, 0xFEu, 0x8Au,
        0x1Eu, 0xBEu, 0xACu, 0x25u, 0x59u, 0x73u, 0x7Cu, 0x15u,
        0x6Fu, 0x34u, 0x33u, 0x76u, 0x13u, 0x78u, 0xADu, 0x40u,
        0x49u, 0x5Cu, 0x47u, 0x2Cu, 0xF0u, 0x24u, 0x37u, 0x11u,
        0xA0u, 0xDAu, 0x83u, 0x70u, 0x01u, 0x08u, 0x86u, 0x1Eu,
        0x94u, 0x3Bu, 0x7Cu, 0xB9u, 0x7Du, 0x53u, 0xC2u, 0xE9u,
        0x86u, 0xA6u, 0xE0u, 0xDBu, 0xA6u, 0xBCu, 0x08u, 0xD6u,
        0x66u, 0xFBu, 0x54u, 0x26u, 0xA7u, 0xA7u, 0x05u, 0x41u,
        0x1Au, 0xD0u, 0x98u, 0xA5u, 0xE6u, 0xF0u, 0x65u, 0x66u,
        0x2Bu, 0x8Bu, 0x60u, 0x73u, 0x5Cu, 0xBBu, 0x70u, 0x9Eu,
        0x2Au, 0x60u, 0x89u, 0x73u, 0xAEu, 0x44u, 0x29u, 0x31u,
        0xC3u, 0xEEu, 0xC5u, 0x42u, 0x61u, 0x0Fu, 0x77u, 0x44u,
        0x4Du, 0xABu, 0x46u, 0x25u, 0xB9u, 0xDDu, 0x9Du, 0x02u,
        0x0Cu, 0xFAu, 0x66u, 0xD5u, 0x6Cu, 0x74u, 0xCEu, 0xFAu,
        0x59u, 0x04u, 0xCAu, 0xB6u, 0xABu, 0x11u, 0xF4u, 0x22u,
        0xE7u, 0xF5u, 0xA4u, 0xFEu, 0xF6u, 0xA3u, 0x25u, 0xB2u,
        0xA1u, 0xE3u, 0xDEu, 0xF5u, 0x29u, 0x05u, 0xE0u, 0x66u,
        0x5Du, 0xB2u, 0x11u, 0xD1u, 0x12u, 0x12u, 0x9Au, 0x34u,
        0x9Eu, 0x3Cu, 0xCBu, 0x50u, 0x85u, 0xD8u, 0x32u, 0x2Du,
        0xD7u, 0xA7u, 0xCBu, 0xE0u, 0x6Bu, 0xEAu, 0x18u, 0x27u,
        0xE5u, 0xE1u, 0xEFu, 0x8Cu, 0x37u, 0x9Au, 0xA8u, 0x9Bu,
        0xB4u, 0x78u, 0x18u, 0xCDu, 0x64u, 0xA1u, 0x20u, 0x74u,
        0x0Du, 0x85u, 0xD5u, 0xB7u, 0x32u, 0xC2u, 0x82u, 0xEEu,
        0xABu, 0x9Cu, 0xE2u, 0x4Eu, 0x9Du, 0xFBu, 0x9Bu, 0xE0u,
        0xE3u, 0xC5u, 0x95u, 0x73u, 0xE9u, 0xE4u, 0x51u, 0xA4u,
        0x28u, 0x9Au, 0xB4u, 0xEDu, 0xE5u, 0x46u, 0xBDu, 0x76u,
        0x8Du, 0xE9u, 0x70u, 0x8Fu, 0x92u, 0x60u, 0x77u, 0x9Eu,
        0x7Fu, 0x6Fu, 0x45u, 0xC7u, 0x87u, 0x02u, 0x86u, 0x9Fu,
        0xABu, 0xEEu, 0x74u, 0x2Bu, 0xDFu, 0xB4u, 0x75u, 0x0Du,
        0x2Au, 0xD6u, 0xB4u, 0xEEu, 0x63u, 0x70u, 0x45u, 0xCEu,
        0xE0u, 0xECu, 0xEEu, 0x01u, 0xABu, 0xDFu, 0x35u, 0x14u,
        0x4Au, 0xEAu, 0x9Au, 0x16u, 0xACu, 0xC1u, 0x6Au, 0x2Cu,
    },
};

/* Secure Application header for the CodeFlash application */
CY_SECTION(".cy_app_header") __USED
static const CYSAF_APPHEADER_Type CYSAF_HEADER =
{
    .objSize        = SI_SIZE,
    .appId          = (SI_APP_VERSION(SI_VERSION_MAJOR, SI_VERSION_MINOR) | SI_APP_ID_SECUREIMG),
    .appAttributes  = 0UL,                                                  /* Reserved */
    .numCores       = 1UL,                                                  /* Only CM0+ */
    .core0Vt        = SI_VT_OFFSET,                                         /* CM0+ VT offset */
    .core0Id        = SI_CPUID | SI_CORE_IDX,                               /* CM0+ core ID */
};

/* Secure Image Digital signature (Populated by cymcuelftool) */
CY_SECTION(".cy_app_signature") __USED CY_ALIGN(4)
static const uint8_t appSignature[SI_SECURE_DIGSIG_SIZE] = {0u};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: startupCM7
 * Summary:
 *  This is the main function.
 * Parameters:
 *  uint8_t coreNo: specifies coreNo to startup (0/1)
 * Retrun:
 *  void
 **********************************************************************************************************************
 */
void startupCM7(uint8_t coreNo)
{
    /* Cy_FB_VerifyApplication verifies digital signature using public key in SFLASH */
    uint32_t (*Cy_FB_VerifyApplication)(uint32_t, uint32_t, uint32_t, cy_stc_crypto_rsa_pub_key_t*)
                = (uint32_t(*)(uint32_t, uint32_t, uint32_t, cy_stc_crypto_rsa_pub_key_t*))(*(uint32_t*)VERIFYAPP_ADDR);
    uint32_t topAddress = (uint32_t)((coreNo == CORE_CM7_0) ? __si_cm7_0_app_address : __si_cm7_1_app_address);
    uint32_t objectSize = *(uint32_t *)topAddress;
    uint32_t sigAddress = topAddress + objectSize;

    /* Verify signature of CM7_x image */
    printf("\r\nErase part of the code flash of CM7_%d to make the verify fail? (y/n) [n]:\r\n", coreNo);
    if (getchar() == 'y')
    {
        cyhal_flash_t cyhal_flash;

        printf("y\r\nErasing...\r\n");

        /* Initialization */
        if (cyhal_flash_init(&cyhal_flash) != CY_RSLT_SUCCESS)
        {
            CY_ASSERT(0);
        }

        /* Enable code flash write function */
        Cy_Flashc_MainWriteEnable();

        /* Erase code flash target sector */
        if (cyhal_flash_erase(&cyhal_flash, topAddress + SECTOR_SIZE) != CY_RSLT_SUCCESS)
        {
            CY_ASSERT(0);
        }

        printf("done\r\n");
    }
    else
    {
        printf("n\r\nContinue without erasing\r\n");
    }

    /* Read out the return code remaining in buffer */
    getchar();

    printf("Verifying CM7_%d(0x%x[byte])...\r\n", coreNo, (unsigned int)objectSize);
    if (Cy_FB_VerifyApplication(topAddress, objectSize, sigAddress, (cy_stc_crypto_rsa_pub_key_t*)PUBLIC_KEY_ADDR) == 1)
    {
        Cy_SysEnableCM7(coreNo, topAddress + 0x100);
        printf("It has been successfully verified and enabled!\r\n");
    }
    else
    {
        printf("Verification has been failed... CM7_%d cannot be enabled\r\n", coreNo);
    }
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Retrun:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    /* Initialize the device and board peripherals */
    if (cybsp_init() != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    if (cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE) != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");

    printf("****************** "
           "code example of Secure Boot configuration "
           "****************** \r\n\n");

    printf("This program comes here means that the CM0+ firmware is already successfully verified by FlashBoot!\r\n\r\n");

    /* verifying CM7_0 then enable it if the verification is ok */
    startupCM7(CORE_CM7_0);

    /* verifying CM7_1 then enable it if the verification is ok */
    startupCM7(CORE_CM7_1);

    for (;;)
    {
        Cy_SysPm_CpuEnterDeepSleep(CY_SYSPM_WAIT_FOR_INTERRUPT);
    }
}

/* [] END OF FILE */
